remote_theme: pmarsceill/just-the-docs
include:
  - index.md
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
logo: "/assets/main.png"

color_scheme: dark

callouts:
  info:
    title: Info
    color: blue
  warning:
    title: Warning
    color: red
